### PR TITLE
GPU/OpenACC Correctness Fixes and Performance Optimizations

### LINKED ISSUE #9: OpenACC or acceleration on GPU

### PR DESCRIPTION
**Pull request by chaseshyu**
This pull request focuses on improving the parallelization of computational kernels and making minor functional adjustments to the codebase. The main theme is updating OpenACC parallel loop directives to leverage both gang and vector parallelism, which should improve performance on supported hardware. There are also minor changes to function signatures, variable initialization.

**Parallelization improvements:**

* Updated all `#pragma acc parallel loop async` directives to `#pragma acc parallel loop gang vector async` or `#pragma acc parallel loop gang vector` in computational kernels across several files (notably `bc.cxx`, `barycentric-fn.cxx`, and `brc-interpolation.cxx`). This enables both gang-level and vector-level parallelism for better utilization of accelerators. [[1]](diffhunk://#diff-14890f72e8d73c778af4086f5e340cdb672f2ca58d81bf6dd36cf1ed7f42beebL16-R16) [[2]](diffhunk://#diff-14890f72e8d73c778af4086f5e340cdb672f2ca58d81bf6dd36cf1ed7f42beebL53-R53) [[3]](diffhunk://#diff-14890f72e8d73c778af4086f5e340cdb672f2ca58d81bf6dd36cf1ed7f42beebL92-R92) [[4]](diffhunk://#diff-75d3e8106169e381c9fd13e4fb3d747fcd881f0e09cba64d2a40f6c0d2fd3c4eL301-R309) [[5]](diffhunk://#diff-75d3e8106169e381c9fd13e4fb3d747fcd881f0e09cba64d2a40f6c0d2fd3c4eL766-R772) [[6]](diffhunk://#diff-75d3e8106169e381c9fd13e4fb3d747fcd881f0e09cba64d2a40f6c0d2fd3c4eL1134-R1135) [[7]](diffhunk://#diff-75d3e8106169e381c9fd13e4fb3d747fcd881f0e09cba64d2a40f6c0d2fd3c4eL1163-R1161) [[8]](diffhunk://#diff-75d3e8106169e381c9fd13e4fb3d747fcd881f0e09cba64d2a40f6c0d2fd3c4eL1232-R1230) [[9]](diffhunk://#diff-75d3e8106169e381c9fd13e4fb3d747fcd881f0e09cba64d2a40f6c0d2fd3c4eL1256-R1254) [[10]](diffhunk://#diff-75d3e8106169e381c9fd13e4fb3d747fcd881f0e09cba64d2a40f6c0d2fd3c4eL1390-R1388) [[11]](diffhunk://#diff-75d3e8106169e381c9fd13e4fb3d747fcd881f0e09cba64d2a40f6c0d2fd3c4eL1399-R1397) [[12]](diffhunk://#diff-75d3e8106169e381c9fd13e4fb3d747fcd881f0e09cba64d2a40f6c0d2fd3c4eL1489-R1487) [[13]](diffhunk://#diff-75d3e8106169e381c9fd13e4fb3d747fcd881f0e09cba64d2a40f6c0d2fd3c4eL1535-R1533) [[14]](diffhunk://#diff-75d3e8106169e381c9fd13e4fb3d747fcd881f0e09cba64d2a40f6c0d2fd3c4eL1957-R1955) [[15]](diffhunk://#diff-75d3e8106169e381c9fd13e4fb3d747fcd881f0e09cba64d2a40f6c0d2fd3c4eL1983-R1981) [[16]](diffhunk://#diff-75d3e8106169e381c9fd13e4fb3d747fcd881f0e09cba64d2a40f6c0d2fd3c4eL2010-R2008) [[17]](diffhunk://#diff-75d3e8106169e381c9fd13e4fb3d747fcd881f0e09cba64d2a40f6c0d2fd3c4eL2050-R2048) [[18]](diffhunk://#diff-75d3e8106169e381c9fd13e4fb3d747fcd881f0e09cba64d2a40f6c0d2fd3c4eL2064-R2062) [[19]](diffhunk://#diff-75d3e8106169e381c9fd13e4fb3d747fcd881f0e09cba64d2a40f6c0d2fd3c4eL2090-R2088) [[20]](diffhunk://#diff-75d3e8106169e381c9fd13e4fb3d747fcd881f0e09cba64d2a40f6c0d2fd3c4eL2103-R2101)
* Added `#pragma acc wait` after certain asynchronous operations to ensure completion before proceeding, improving correctness and synchronization. [[1]](diffhunk://#diff-75d3e8106169e381c9fd13e4fb3d747fcd881f0e09cba64d2a40f6c0d2fd3c4eL1134-R1135) [[2]](diffhunk://#diff-f3cc4fee53af7a6b632bf30349928722e30d8d3bcbefb0373e5ec2881d149f70R281-L288) [[3]](diffhunk://#diff-f3cc4fee53af7a6b632bf30349928722e30d8d3bcbefb0373e5ec2881d149f70R301-R302)

**Continuous integration and build workflow enhancements:**

* Updated `.github/workflows/nvc-build.yml` to:
  - Build on `master` and `*gpu*` branches.
  - Use `ubuntu-latest` runners instead of `self-hosted`.
  - Upgrade `actions/checkout` to v4.
  - Consolidate and simplify build steps, leveraging environment variables and more robust dependency installation.
  - Focus builds on GPU targets, with CPU debug builds commented out for now.

**Minor improvements and bug fixes:**

* Changed the KD-tree search in `prepare_interpolation` to use all nodes (`var.nnode`) instead of just one, likely fixing a bug in barycentric node interpolation neighbor search.
* Refactored marker coordinate calculation to avoid unnecessary heap allocation and deletion, using stack allocation instead.

### CODE REVIEW

File: bc.cxx [hunk 1]
```diff
@@ -1145,7 +1143,7 @@ void apply_stress_bcs(const Param& param, const Variables& var, array_t& force)
 
         int bound, nbdry_nodes;
 
-        #pragma acc kernels async
+        #pragma acc kernels
```
Comment (tan2) [inline bc.cxx:737]: The async clause is removed, why?

File: bc.cxx [hunk 2]
```diff
@@ -298,17 +298,15 @@ void apply_vbcs(const Param &param, const Variables &var, array_t &vel)
     double bc_vx0r1 = bc.vbc_val_x0_ratio1;
     double bc_vx0r2 = bc.vbc_val_x0_ratio2;
 
-#ifdef THREED
-    #pragma acc parallel loop async
-#else
+#ifndef THREED
     double zmin = 0;
     for (int k=0; k<var.nnode; ++k) {
```
Comment (tan2) [inline bc.cxx:322]: Probably need acc for this loop?

File: markerset.cxx [hunk 3]
```diff
@@ -1265,124 +1299,126 @@ namespace {
...
+            int e = unplenished_elems[i].first;
+            int start = mk_start[i];
+
+            for (int j=0; j<nneed_mk[i]; ++j) {
+                int m_idx = start + j;
+                int m = neighbors[m_idx].idx;
+                double *x = queries[m_idx];
+
+                int mt = ms.get_mattype(m);
+                double ti = ms.get_time(m);
```
[the remark this answers is not in the document]
Comment (tan2) [reply markerset.cxx:1409]: Is it possible that `neighbors[m_idx].idx` is -1? If yes, this is a bug. If no, please add a short comment to explain why. This comment will help readers to understand the code locally.

**Review by tan2 — CHANGES_REQUESTED** [review]

File: bc.cxx (hunk 1 above)
Comment (chaseshyu) [reply bc.cxx:737]: The operation in this acc kernels is to determine the bounds of async loops that will come after. These bound variables must be determined before submitting the async jobs, so they cannot be in the GPU async jobs queue.

File: bc.cxx (hunk 2 above)
Comment (chaseshyu) [reply bc.cxx:322]: This suggestion has been implemented in this commit c1746f63de5bb9d6f6c7b2800c7752d4b5cb7cda .

File: markerset.cxx (hunk 3 above)
[the remark this answers is not in the document]
Comment (chaseshyu) [reply markerset.cxx:1409]: idx might be -1. A check for -1 has been implemented in this commit 26de76025f8d3af71c5237ca8be782e55f871d28.

**Comment by chaseshyu** [comment]
@tan2 The conflict in this PR has been resolved and is now ready for merging.

**Review by tan2 — APPROVED** [review]
